// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shpoowjsmmvquwvzriat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNocG9vd2pzbW12cXV3dnpyaWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjcxMzYsImV4cCI6MjA2NTY0MzEzNn0.PlpW9cqYjRVCFHq7RJzbZNKkSzShZsCxGzXxQVKyhP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);